"use client";

import { useRouter } from "next/navigation";
import { useEffect, useRef, useState } from "react";
import type { QrImage } from "@/lib/qr";

const RETRY_MS = 5000;

// Shows the session QR and swaps in a fresh one before the old one expires.
// If a refresh fails the code is covered rather than left on screen stale.
export function QrDisplay({
  sessionId,
  initial,
}: {
  sessionId: string;
  initial: QrImage;
}) {
  const router = useRouter();
  const [qr, setQr] = useState(initial);
  const [offline, setOffline] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout>>(undefined);

  useEffect(() => {
    let stopped = false;

    async function refresh() {
      clearTimeout(timer.current);
      let delay = RETRY_MS;
      try {
        const res = await fetch(`/api/sessions/${sessionId}/qr`, {
          cache: "no-store",
        });
        if (stopped) return;
        if (res.status === 409 || res.status === 404 || res.status === 401) {
          // Closed, removed or signed out: let the server render decide.
          router.refresh();
          return;
        }
        if (!res.ok) throw new Error(`HTTP ${res.status}`);
        const next = (await res.json()) as QrImage;
        if (stopped) return;
        setQr(next);
        setOffline(false);
        delay = next.rotateInSeconds * 1000;
      } catch {
        if (stopped) return;
        setOffline(true);
      }
      timer.current = setTimeout(refresh, delay);
    }

    // A backgrounded tab may have skipped a rotation.
    function onVisible() {
      if (document.visibilityState === "visible") refresh();
    }

    timer.current = setTimeout(refresh, initial.rotateInSeconds * 1000);
    document.addEventListener("visibilitychange", onVisible);
    return () => {
      stopped = true;
      clearTimeout(timer.current);
      document.removeEventListener("visibilitychange", onVisible);
    };
  }, [sessionId, initial.rotateInSeconds, router]);

  return (
    // A white plate seated in a tray, so the code reads as a physical object.
    <div className="w-full animate-rise rounded-[2.25rem] bg-ink/[0.04] p-2 ring-1 ring-line lg:w-[min(64dvh,34rem)]">
      <div className="relative overflow-hidden rounded-[1.75rem] bg-white p-3 shadow-plate sm:p-5">
        <div
          key={qr.expiresAt}
          aria-label="Attendance QR code"
          role="img"
          className="aspect-square w-full animate-fade [&>svg]:h-full [&>svg]:w-full"
          // SVG generated by our own server from a signed URL.
          dangerouslySetInnerHTML={{ __html: qr.svg }}
        />
        {/* Runs down until the next code replaces this one. */}
        {!offline && (
          <div
            key={`bar-${qr.expiresAt}`}
            aria-hidden="true"
            className="absolute inset-x-6 bottom-1.5 h-0.5 origin-left animate-deplete rounded-full bg-ink/40 motion-reduce:hidden sm:bottom-2"
            style={{ animationDuration: `${qr.rotateInSeconds}s` }}
          />
        )}
        {offline && (
          <div
            role="status"
            className="absolute inset-0 flex animate-fade flex-col items-center justify-center gap-1 bg-white/95 text-center"
          >
            <p className="text-2xl font-semibold tracking-tight">Reconnecting…</p>
            <p className="text-muted">The code will return when the connection does.</p>
          </div>
        )}
      </div>
    </div>
  );
}
